[package]
name = "mesh-rand-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.3"
mesh-rand = { path = "../mesh-rand" }
mint = "0.5.9"
plotters = "0.3.4"
rand = "0.8.5"
